### PR TITLE
chore: fix typo.

### PR DESCRIPTION
**Pull request by YDX-2147483647**
Gruaduate → Graduate.

### CODE REVIEW

**Review by fky2015 — APPROVED** [review]
Great work!

I noticed a similar error in tests/doctor-thesis/README.md. Could you help me fix it?

**Comment by YDX-2147483647** [comment]
✓

**Review by fky2015 — APPROVED** [review]
You could merge this PR once all checks pass. Thank you for your contribution again. :+1:

**Comment by YDX-2147483647** [comment]
Thanks. All checks have passed, but I don't have write access to the repo …

**Pull request merged**
