### PR TITLE
Release v3.6.3

### LINKED ISSUE #413: [Release Tracker] <v3.6.3>
- [x] 提升版本号到最新
- [x] 生成 CHANGELOG
- [x] 通过单元测试
- [ ] `bithesis` 是否需要更新
  - [ ] 上传 CTAN
- [x] 上传新的模板到 Overleaf
- [ ] 模板是否需要更新
  - [ ] 发布新的 Release

### PR DESCRIPTION
**Pull request by YDX-2147483647**
Resolves #413

### CODE REVIEW

**Comment by fky2015** [comment]
Need rebase

**Comment by YDX-2147483647** [comment]
`make doc`（`latexmk -xelatex bithesis.dtx`）产生了`bithesis.luabridge.lua`。这是什么？是否要加入仓库？

```lua
local ran_ok,err=pcall(function()local ran_ok,kpse=pcall(require, "kpse")if ran_ok then kpse.set_program_name("luatex")end a
ssert(load("print(os.getenv(\"TEXMF_OUTPUT_DIRECTORY\")or\".\")"))()end)if not ran_ok then local file=io.open("./bithesis.lu
abridge.err","w")if file then file:write(err.."\n")file:close()end print('\\begingroup\\ExplSyntaxOn\\csname msg_error:nnvv\
\endcsname{luabridge}{failed-to-execute}{g_luabridge_output_dirname_str}{g_luabridge_error_output_filename_str}\\endgroup')e
nd
```

<details>
<summary>部分日志</summary>

```log
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/latex/fontawesome5/tufontawesomebr
ands.fd))))
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/generic/dirtree/dirtree.sty
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/generic/dirtree/dirtree.tex
`dirtree' v0.32, 2012/12/11 (jcc)))
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/latex/metalogo/metalogo.sty
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/generic/iftex/ifxetex.sty))
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/latex/markdown/markdown.sty
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/generic/markdown/markdown.tex
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/generic/lt3luabridge/lt3luabridge.
tex) (|texlua ./bithesis.luabridge.lua)))
(d:/ProgramFiles/texlive/2024/texmf-dist/tex/latex/markdown/markdownthemewitiko
_markdown_defaults.sty
```

</details>

**Comment by fky2015** [comment]
> `make doc`（`latexmk -xelatex bithesis.dtx`）产生了`bithesis.luabridge.lua`。这是什么？是否要加入仓库？

我没有遇到过，不要加入。PDF 能正常生成就行。

**Comment by fky2015** [comment]
看起来 CTAN 的使用方式改变了，这个我回头弄吧。我们先合入这个 MR。

**Comment by YDX-2147483647** [comment]
`make overleaf`可能要改一下，现在`main.tex`在压缩包中位于`overleaf/{}/main.tex`，导入后是`{}/main.tex`，多套一层目录，导致字数统计用不了。

虽然这明显是Overleaf的bug，但人家文档专门写了……

> To ensure Overleaf features work correctly, we recommend placing the project's `main.tex` file in the project's **top-level folder**. For example, features affected include [jump-to-location](https://cn.overleaf.com/learn/how-to/Can%27t_find_%60jump_to_location%27_arrows), [word count](https://cn.overleaf.com/learn/how-to/Is_there_a_way_to_run_a_word_count_that_doesn%27t_include_LaTeX_commands%3F) and scripts like [makeglossaries](https://cn.overleaf.com/learn/latex/Glossaries) etc.

[Can I choose which file is the main tex file in a project on Overleaf? - Overleaf, Online LaTeX Editor](https://www.overleaf.com/learn/how-to/Can_I_choose_which_file_is_the_main_tex_file_in_a_project_on_Overleaf%3F)

**Comment by fky2015** [comment]
> `make overleaf`可能要改一下。
> 
> 现在`main.tex`在压缩包中位于`overleaf/{}/main.tex`，导入后是`{}/main.tex`，多套一层目录，导致字数统计用不了。
> 
> 虽然这明显是Overleaf的bug，但人家文档专门写了……
> 
> > To ensure Overleaf features work correctly, we recommend placing the project's `main.tex` file in the project's **top-level folder**. For example, features affected include [jump-to-location](https://cn.overleaf.com/learn/how-to/Can%27t_find_%60jump_to_location%27_arrows), [word count](https://cn.overleaf.com/learn/how-to/Is_there_a_way_to_run_a_word_count_that_doesn%27t_include_LaTeX_commands%3F) and scripts like [makeglossaries](https://cn.overleaf.com/learn/latex/Glossaries) etc.
> 
> [Can I choose which file is the main tex file in a project on Overleaf? - Overleaf, Online LaTeX Editor](https://www.overleaf.com/learn/how-to/Can_I_choose_which_file_is_the_main_tex_file_in_a_project_on_Overleaf%3F)

已经解决， rebase 即可

**Review by fky2015 — APPROVED** [review]

**Pull request merged**
